-- ZB Interieur: 155 Bilder aus "image manager pro - bilder" (7 Hersteller-Ordner).
-- Marke = Ordner, Name = Dateiname ohne Zahlen, Produktart und Bereich nach Bildinhalt.
-- Bilder liegen auf der ZB-Website unter /images/imp/. Überspringt bereits eingetragene Bilder. Mehrfach ausführbar.
insert into public.images (tenant_id, website_id, filename, name, text, note, category1, category2, category3, category4, url, format, width, height, file_size, status, sync_status, external_id, updated_at)
select
  (select id from public.tenants where slug = 'digitale-medien-319ef552'), null, p.filename, p.name, '', 'Preis auf Anfrage', p.brand, p.type, p.room, '', p.url, 'WEBP', p.width, p.height, p.size,
  'active', 'pending', p.key,
  now() - make_interval(secs => p.ord)
from (values
  (0, 'zb-upload:/images/imp/al2/echo-c.webp', 'AL2', 'Tisch', 'Esszimmer', 'Echo C', 'https://zb-interieur.netlify.app/images/imp/al2/echo-c.webp', 'echo-c.webp', 1800, 1200, 63978),
  (1, 'zb-upload:/images/imp/al2/eterna-a.webp', 'AL2', 'Sideboard', 'Wohnzimmer', 'Eterna A', 'https://zb-interieur.netlify.app/images/imp/al2/eterna-a.webp', 'eterna-a.webp', 1800, 1200, 33428),
  (2, 'zb-upload:/images/imp/al2/laas-low-table.webp', 'AL2', 'Tisch', 'Wohnzimmer', 'Laas Low Table', 'https://zb-interieur.netlify.app/images/imp/al2/laas-low-table.webp', 'laas-low-table.webp', 1600, 800, 16624),
  (3, 'zb-upload:/images/imp/al2/regal.webp', 'AL2', 'Regal', 'Wohnzimmer', 'Regal', 'https://zb-interieur.netlify.app/images/imp/al2/regal.webp', 'regal.webp', 770, 900, 32920),
  (4, 'zb-upload:/images/imp/al2/tisch-schwarz.webp', 'AL2', 'Tisch', 'Esszimmer', 'Tisch Schwarz', 'https://zb-interieur.netlify.app/images/imp/al2/tisch-schwarz.webp', 'tisch-schwarz.webp', 770, 900, 74688),
  (5, 'zb-upload:/images/imp/al2/bonet-sofa-dakry-console.webp', 'AL2', 'Sofa', 'Wohnzimmer', 'Bonet Sofa Dakry Console', 'https://zb-interieur.netlify.app/images/imp/al2/bonet-sofa-dakry-console.webp', 'bonet-sofa-dakry-console.webp', 1800, 1080, 333482),
  (6, 'zb-upload:/images/imp/al2/chairs-siena.webp', 'AL2', 'Stuhl', 'Esszimmer', 'Chairs Siena', 'https://zb-interieur.netlify.app/images/imp/al2/chairs-siena.webp', 'chairs-siena.webp', 471, 570, 33078),
  (7, 'zb-upload:/images/imp/al2/composition.webp', 'AL2', 'Sofa', 'Wohnzimmer', 'Composition', 'https://zb-interieur.netlify.app/images/imp/al2/composition.webp', 'composition.webp', 1560, 1040, 136798),
  (8, 'zb-upload:/images/imp/al2/composition-2.webp', 'AL2', 'Tisch', 'Esszimmer', 'Composition', 'https://zb-interieur.netlify.app/images/imp/al2/composition-2.webp', 'composition-2.webp', 1290, 860, 96296),
  (9, 'zb-upload:/images/imp/al2/consoles-echo-walnut.webp', 'AL2', 'Sideboard', 'Flur', 'Consoles Echo Walnut', 'https://zb-interieur.netlify.app/images/imp/al2/consoles-echo-walnut.webp', 'consoles-echo-walnut.webp', 570, 535, 23178),
  (10, 'zb-upload:/images/imp/al2/dakry-a-dakry-a.webp', 'AL2', 'Tisch', 'Wohnzimmer', 'Dakry A Dakry A', 'https://zb-interieur.netlify.app/images/imp/al2/dakry-a-dakry-a.webp', 'dakry-a-dakry-a.webp', 1800, 1200, 26816),
  (11, 'zb-upload:/images/imp/al2/dining-tables-zephyr-facco.webp', 'AL2', 'Tisch', 'Esszimmer', 'Dining Tables Zephyr Facco', 'https://zb-interieur.netlify.app/images/imp/al2/dining-tables-zephyr-facco.webp', 'dining-tables-zephyr-facco.webp', 1296, 864, 16858),
  (12, 'zb-upload:/images/imp/al2/dining-tables-zephyr-facco-2.webp', 'AL2', 'Tisch', 'Esszimmer', 'Dining Tables Zephyr Facco', 'https://zb-interieur.netlify.app/images/imp/al2/dining-tables-zephyr-facco-2.webp', 'dining-tables-zephyr-facco-2.webp', 1296, 864, 101724),
  (13, 'zb-upload:/images/imp/al2/echo-oak-clara-chair-eterna-a-sideboard.webp', 'AL2', 'Tisch', 'Esszimmer', 'Echo Oak Clara Chair Eterna A Sideboard', 'https://zb-interieur.netlify.app/images/imp/al2/echo-oak-clara-chair-eterna-a-sideboard.webp', 'echo-oak-clara-chair-eterna-a-sideboard.webp', 1800, 1013, 157884),
  (14, 'zb-upload:/images/imp/al2/echo-walnut-clara-chair.webp', 'AL2', 'Tisch', 'Esszimmer', 'Echo Walnut Clara Chair', 'https://zb-interieur.netlify.app/images/imp/al2/echo-walnut-clara-chair.webp', 'echo-walnut-clara-chair.webp', 1800, 1080, 383490),
  (15, 'zb-upload:/images/imp/al2/eterna-a-sideboard.webp', 'AL2', 'Sideboard', 'Wohnzimmer', 'Eterna A Sideboard', 'https://zb-interieur.netlify.app/images/imp/al2/eterna-a-sideboard.webp', 'eterna-a-sideboard.webp', 1800, 1013, 281384),
  (16, 'zb-upload:/images/imp/al2/low-table-laas.webp', 'AL2', 'Tisch', 'Wohnzimmer', 'Low Table Laas', 'https://zb-interieur.netlify.app/images/imp/al2/low-table-laas.webp', 'low-table-laas.webp', 1500, 934, 194088),
  (17, 'zb-upload:/images/imp/al2/low-table-meguru-oak.webp', 'AL2', 'Tisch', 'Wohnzimmer', 'Low Table Meguru Oak', 'https://zb-interieur.netlify.app/images/imp/al2/low-table-meguru-oak.webp', 'low-table-meguru-oak.webp', 770, 462, 9562),
  (18, 'zb-upload:/images/imp/al2/low-tables-laas-marble.webp', 'AL2', 'Tisch', 'Wohnzimmer', 'Low Tables Laas Marble', 'https://zb-interieur.netlify.app/images/imp/al2/low-tables-laas-marble.webp', 'low-tables-laas-marble.webp', 1500, 1000, 115472),
  (19, 'zb-upload:/images/imp/al2/mosiko-sideboard.webp', 'AL2', 'Sideboard', 'Wohnzimmer', 'Mosiko Sideboard', 'https://zb-interieur.netlify.app/images/imp/al2/mosiko-sideboard.webp', 'mosiko-sideboard.webp', 1800, 1221, 150988),
  (20, 'zb-upload:/images/imp/al2/mosiko-sideboard-2.webp', 'AL2', 'Sideboard', 'Wohnzimmer', 'Mosiko Sideboard', 'https://zb-interieur.netlify.app/images/imp/al2/mosiko-sideboard-2.webp', 'mosiko-sideboard-2.webp', 1800, 1219, 260698),
  (21, 'zb-upload:/images/imp/al2/mosiko-sideboard-3.webp', 'AL2', 'Sideboard', 'Wohnzimmer', 'Mosiko Sideboard', 'https://zb-interieur.netlify.app/images/imp/al2/mosiko-sideboard-3.webp', 'mosiko-sideboard-3.webp', 872, 978, 52062),
  (22, 'zb-upload:/images/imp/al2/mosiko-sideboard-4.webp', 'AL2', 'Sideboard', 'Wohnzimmer', 'Mosiko Sideboard', 'https://zb-interieur.netlify.app/images/imp/al2/mosiko-sideboard-4.webp', 'mosiko-sideboard-4.webp', 1800, 1020, 26414),
  (23, 'zb-upload:/images/imp/al2/sideboard.webp', 'AL2', 'Sideboard', 'Wohnzimmer', 'Sideboard', 'https://zb-interieur.netlify.app/images/imp/al2/sideboard.webp', 'sideboard.webp', 770, 900, 64282),
  (24, 'zb-upload:/images/imp/al2/sofa-rostfarbe.webp', 'AL2', 'Sofa', 'Wohnzimmer', 'Sofa Rostfarbe', 'https://zb-interieur.netlify.app/images/imp/al2/sofa-rostfarbe.webp', 'sofa-rostfarbe.webp', 770, 900, 97504),
  (25, 'zb-upload:/images/imp/al2/sofas-lazy-upholstered.webp', 'AL2', 'Sofa', 'Wohnzimmer', 'Sofas Lazy Upholstered', 'https://zb-interieur.netlify.app/images/imp/al2/sofas-lazy-upholstered.webp', 'sofas-lazy-upholstered.webp', 1500, 1000, 250104),
  (26, 'zb-upload:/images/imp/al2/sofas-low-tables-arch-hyper.webp', 'AL2', 'Sofa', 'Wohnzimmer', 'Sofas Low Tables Arch Hyper', 'https://zb-interieur.netlify.app/images/imp/al2/sofas-low-tables-arch-hyper.webp', 'sofas-low-tables-arch-hyper.webp', 1500, 892, 153792),
  (27, 'zb-upload:/images/imp/bonaldo/art.webp', 'Bonaldo', 'Tisch', 'Esszimmer', 'Art', 'https://zb-interieur.netlify.app/images/imp/bonaldo/art.webp', 'art.webp', 1200, 675, 136032),
  (28, 'zb-upload:/images/imp/bonaldo/art-2.webp', 'Bonaldo', 'Tisch', 'Esszimmer', 'Art', 'https://zb-interieur.netlify.app/images/imp/bonaldo/art-2.webp', 'art-2.webp', 1200, 675, 126998),
  (29, 'zb-upload:/images/imp/bonaldo/art-3.webp', 'Bonaldo', 'Tisch', 'Esszimmer', 'Art', 'https://zb-interieur.netlify.app/images/imp/bonaldo/art-3.webp', 'art-3.webp', 1200, 675, 103630),
  (30, 'zb-upload:/images/imp/bonaldo/flairon-coffe-tables.webp', 'Bonaldo', 'Tisch', 'Wohnzimmer', 'Flairon Coffe Tables', 'https://zb-interieur.netlify.app/images/imp/bonaldo/flairon-coffe-tables.webp', 'flairon-coffe-tables.webp', 1200, 800, 71550),
  (31, 'zb-upload:/images/imp/bonaldo/flairon-coffe-tables-2.webp', 'Bonaldo', 'Tisch', 'Wohnzimmer', 'Flairon Coffe Tables', 'https://zb-interieur.netlify.app/images/imp/bonaldo/flairon-coffe-tables-2.webp', 'flairon-coffe-tables-2.webp', 1200, 800, 16320),
  (32, 'zb-upload:/images/imp/bonaldo/flatiron.webp', 'Bonaldo', 'Tisch', 'Esszimmer', 'Flatiron', 'https://zb-interieur.netlify.app/images/imp/bonaldo/flatiron.webp', 'flatiron.webp', 1200, 800, 71094),
  (33, 'zb-upload:/images/imp/bonaldo/geometric-table.webp', 'Bonaldo', 'Tisch', 'Esszimmer', 'Geometric Table', 'https://zb-interieur.netlify.app/images/imp/bonaldo/geometric-table.webp', 'geometric-table.webp', 1200, 675, 129650),
  (34, 'zb-upload:/images/imp/bonaldo/geometric-table-2.webp', 'Bonaldo', 'Tisch', 'Esszimmer', 'Geometric Table', 'https://zb-interieur.netlify.app/images/imp/bonaldo/geometric-table-2.webp', 'geometric-table-2.webp', 1200, 675, 101444),
  (35, 'zb-upload:/images/imp/bonaldo/hippos.webp', 'Bonaldo', 'Tisch', 'Esszimmer', 'Hippos', 'https://zb-interieur.netlify.app/images/imp/bonaldo/hippos.webp', 'hippos.webp', 1200, 675, 48924),
  (36, 'zb-upload:/images/imp/bonaldo/honeymoon.webp', 'Bonaldo', 'Bett', 'Schlafzimmer', 'Honeymoon', 'https://zb-interieur.netlify.app/images/imp/bonaldo/honeymoon.webp', 'honeymoon.webp', 1200, 675, 82102),
  (37, 'zb-upload:/images/imp/bonaldo/louver.webp', 'Bonaldo', 'Tisch', 'Esszimmer', 'Louver', 'https://zb-interieur.netlify.app/images/imp/bonaldo/louver.webp', 'louver.webp', 1200, 675, 75328),
  (38, 'zb-upload:/images/imp/bonaldo/lovy-armchair.webp', 'Bonaldo', 'Sessel', 'Wohnzimmer', 'Lovy Armchair', 'https://zb-interieur.netlify.app/images/imp/bonaldo/lovy-armchair.webp', 'lovy-armchair.webp', 1200, 675, 257566),
  (39, 'zb-upload:/images/imp/bonaldo/lovy-armchair-2.webp', 'Bonaldo', 'Sessel', 'Wohnzimmer', 'Lovy Armchair', 'https://zb-interieur.netlify.app/images/imp/bonaldo/lovy-armchair-2.webp', 'lovy-armchair-2.webp', 1080, 608, 113718),
  (40, 'zb-upload:/images/imp/bonaldo/matrimoniali-squaring.webp', 'Bonaldo', 'Bett', 'Schlafzimmer', 'Matrimoniali Squaring', 'https://zb-interieur.netlify.app/images/imp/bonaldo/matrimoniali-squaring.webp', 'matrimoniali-squaring.webp', 400, 608, 28606),
  (41, 'zb-upload:/images/imp/bonaldo/matrimoniali-squaring-2.webp', 'Bonaldo', 'Bett', 'Schlafzimmer', 'Matrimoniali Squaring', 'https://zb-interieur.netlify.app/images/imp/bonaldo/matrimoniali-squaring-2.webp', 'matrimoniali-squaring-2.webp', 1200, 675, 172126),
  (42, 'zb-upload:/images/imp/bonaldo/matrimoniali-tara.webp', 'Bonaldo', 'Bett', 'Schlafzimmer', 'Matrimoniali Tara', 'https://zb-interieur.netlify.app/images/imp/bonaldo/matrimoniali-tara.webp', 'matrimoniali-tara.webp', 1200, 783, 71140),
  (43, 'zb-upload:/images/imp/bonaldo/matrimoniali.webp', 'Bonaldo', 'Bett', 'Schlafzimmer', 'Matrimoniali', 'https://zb-interieur.netlify.app/images/imp/bonaldo/matrimoniali.webp', 'matrimoniali.webp', 1200, 1391, 147080),
  (44, 'zb-upload:/images/imp/bonaldo/maximilian.webp', 'Bonaldo', 'Sofa', 'Wohnzimmer', 'Maximilian', 'https://zb-interieur.netlify.app/images/imp/bonaldo/maximilian.webp', 'maximilian.webp', 1200, 675, 144718),
  (45, 'zb-upload:/images/imp/bonaldo/maximilian-2.webp', 'Bonaldo', 'Sofa', 'Wohnzimmer', 'Maximilian', 'https://zb-interieur.netlify.app/images/imp/bonaldo/maximilian-2.webp', 'maximilian-2.webp', 1200, 675, 145704),
  (46, 'zb-upload:/images/imp/bonaldo/palazzo.webp', 'Bonaldo', 'Tisch', 'Esszimmer', 'Palazzo', 'https://zb-interieur.netlify.app/images/imp/bonaldo/palazzo.webp', 'palazzo.webp', 1200, 800, 109844),
  (47, 'zb-upload:/images/imp/fine/embrace.webp', 'Fine', 'Bett', 'Schlafzimmer', 'Embrace', 'https://zb-interieur.netlify.app/images/imp/fine/embrace.webp', 'embrace.webp', 950, 1030, 67878),
  (48, 'zb-upload:/images/imp/fine/embrace-2.webp', 'Fine', 'Bett', 'Schlafzimmer', 'Embrace', 'https://zb-interieur.netlify.app/images/imp/fine/embrace-2.webp', 'embrace-2.webp', 950, 1030, 152352),
  (49, 'zb-upload:/images/imp/fine/kira.webp', 'Fine', 'Bett', 'Schlafzimmer', 'Kira', 'https://zb-interieur.netlify.app/images/imp/fine/kira.webp', 'kira.webp', 1260, 1800, 85808),
  (50, 'zb-upload:/images/imp/fine/kira-2.webp', 'Fine', 'Bett', 'Schlafzimmer', 'Kira', 'https://zb-interieur.netlify.app/images/imp/fine/kira-2.webp', 'kira-2.webp', 1800, 1125, 71372),
  (51, 'zb-upload:/images/imp/fine/phase.webp', 'Fine', 'Bett', 'Schlafzimmer', 'Phase', 'https://zb-interieur.netlify.app/images/imp/fine/phase.webp', 'phase.webp', 1800, 1125, 103100),
  (52, 'zb-upload:/images/imp/fine/bold.webp', 'Fine', 'Bett', 'Schlafzimmer', 'Bold', 'https://zb-interieur.netlify.app/images/imp/fine/bold.webp', 'bold.webp', 950, 1030, 106860),
  (53, 'zb-upload:/images/imp/fine/clip.webp', 'Fine', 'Bett', 'Schlafzimmer', 'Clip', 'https://zb-interieur.netlify.app/images/imp/fine/clip.webp', 'clip.webp', 950, 1030, 92986),
  (54, 'zb-upload:/images/imp/fine/clip-2.webp', 'Fine', 'Bett', 'Schlafzimmer', 'Clip', 'https://zb-interieur.netlify.app/images/imp/fine/clip-2.webp', 'clip-2.webp', 950, 1030, 107400),
  (55, 'zb-upload:/images/imp/fine/cube.webp', 'Fine', 'Bett', 'Schlafzimmer', 'Cube', 'https://zb-interieur.netlify.app/images/imp/fine/cube.webp', 'cube.webp', 1200, 1301, 87672),
  (56, 'zb-upload:/images/imp/fine/daxbed.webp', 'Fine', 'Daybed', 'Schlafzimmer', 'Daxbed', 'https://zb-interieur.netlify.app/images/imp/fine/daxbed.webp', 'daxbed.webp', 1667, 1800, 104212),
  (57, 'zb-upload:/images/imp/fine/daybed.webp', 'Fine', 'Daybed', 'Schlafzimmer', 'Daybed', 'https://zb-interieur.netlify.app/images/imp/fine/daybed.webp', 'daybed.webp', 1760, 1400, 200008),
  (58, 'zb-upload:/images/imp/fine/daybed-2.webp', 'Fine', 'Daybed', 'Schlafzimmer', 'Daybed', 'https://zb-interieur.netlify.app/images/imp/fine/daybed-2.webp', 'daybed-2.webp', 1800, 938, 129410),
  (59, 'zb-upload:/images/imp/fine/fluff.webp', 'Fine', 'Bett', 'Schlafzimmer', 'Fluff', 'https://zb-interieur.netlify.app/images/imp/fine/fluff.webp', 'fluff.webp', 1800, 1125, 143562),
  (60, 'zb-upload:/images/imp/fine/lean-on-me.webp', 'Fine', 'Bett', 'Schlafzimmer', 'Lean On Me', 'https://zb-interieur.netlify.app/images/imp/fine/lean-on-me.webp', 'lean-on-me.webp', 1800, 1152, 172618),
  (61, 'zb-upload:/images/imp/fine/lean-on-me-2.webp', 'Fine', 'Bett', 'Schlafzimmer', 'Lean On Me', 'https://zb-interieur.netlify.app/images/imp/fine/lean-on-me-2.webp', 'lean-on-me-2.webp', 1440, 1800, 326720),
  (62, 'zb-upload:/images/imp/fine/nest.webp', 'Fine', 'Bett', 'Schlafzimmer', 'Nest', 'https://zb-interieur.netlify.app/images/imp/fine/nest.webp', 'nest.webp', 1660, 1800, 201258),
  (63, 'zb-upload:/images/imp/fine/nest-2.webp', 'Fine', 'Bett', 'Schlafzimmer', 'Nest', 'https://zb-interieur.netlify.app/images/imp/fine/nest-2.webp', 'nest-2.webp', 950, 1030, 107128),
  (64, 'zb-upload:/images/imp/fine/pillow.webp', 'Fine', 'Bett', 'Schlafzimmer', 'Pillow', 'https://zb-interieur.netlify.app/images/imp/fine/pillow.webp', 'pillow.webp', 1200, 1301, 80476),
  (65, 'zb-upload:/images/imp/fine/soft.webp', 'Fine', 'Bett', 'Schlafzimmer', 'Soft', 'https://zb-interieur.netlify.app/images/imp/fine/soft.webp', 'soft.webp', 1660, 1800, 152694),
  (66, 'zb-upload:/images/imp/fine/soft-2.webp', 'Fine', 'Bett', 'Schlafzimmer', 'Soft', 'https://zb-interieur.netlify.app/images/imp/fine/soft-2.webp', 'soft-2.webp', 1660, 1800, 264956),
  (67, 'zb-upload:/images/imp/giellesse/composition.webp', 'Giellesse', 'Schrank', 'Wohnzimmer', 'Composition', 'https://zb-interieur.netlify.app/images/imp/giellesse/composition.webp', 'composition.webp', 1800, 1017, 256684),
  (68, 'zb-upload:/images/imp/giellesse/composition-2.webp', 'Giellesse', 'Sideboard', 'Wohnzimmer', 'Composition', 'https://zb-interieur.netlify.app/images/imp/giellesse/composition-2.webp', 'composition-2.webp', 1800, 1017, 262860),
  (69, 'zb-upload:/images/imp/giellesse/composition-3.webp', 'Giellesse', 'Sideboard', 'Wohnzimmer', 'Composition', 'https://zb-interieur.netlify.app/images/imp/giellesse/composition-3.webp', 'composition-3.webp', 1800, 1017, 187544),
  (70, 'zb-upload:/images/imp/giellesse/composition-4.webp', 'Giellesse', 'Sideboard', 'Wohnzimmer', 'Composition', 'https://zb-interieur.netlify.app/images/imp/giellesse/composition-4.webp', 'composition-4.webp', 1800, 1017, 184360),
  (71, 'zb-upload:/images/imp/giellesse/composition-5.webp', 'Giellesse', 'Regal', 'Wohnzimmer', 'Composition', 'https://zb-interieur.netlify.app/images/imp/giellesse/composition-5.webp', 'composition-5.webp', 1800, 1173, 287332),
  (72, 'zb-upload:/images/imp/giellesse/composition-6.webp', 'Giellesse', 'Schrank', 'Schlafzimmer', 'Composition', 'https://zb-interieur.netlify.app/images/imp/giellesse/composition-6.webp', 'composition-6.webp', 1800, 1236, 227836),
  (73, 'zb-upload:/images/imp/giellesse/composition-7.webp', 'Giellesse', 'Regal', 'Esszimmer', 'Composition', 'https://zb-interieur.netlify.app/images/imp/giellesse/composition-7.webp', 'composition-7.webp', 1800, 1208, 123476),
  (74, 'zb-upload:/images/imp/giellesse/composition-8.webp', 'Giellesse', 'Regal', 'Wohnzimmer', 'Composition', 'https://zb-interieur.netlify.app/images/imp/giellesse/composition-8.webp', 'composition-8.webp', 1800, 1140, 169254),
  (75, 'zb-upload:/images/imp/giellesse/composition-9.webp', 'Giellesse', 'Regal', 'Wohnzimmer', 'Composition', 'https://zb-interieur.netlify.app/images/imp/giellesse/composition-9.webp', 'composition-9.webp', 1800, 1136, 243716),
  (76, 'zb-upload:/images/imp/giellesse/giellesse-sideboards.webp', 'Giellesse', 'Schrank', 'Wohnzimmer', 'Giellesse Sideboards', 'https://zb-interieur.netlify.app/images/imp/giellesse/giellesse-sideboards.webp', 'giellesse-sideboards.webp', 1800, 1172, 150268),
  (77, 'zb-upload:/images/imp/giellesse/giellesse-sideboards-2.webp', 'Giellesse', 'Sideboard', 'Wohnzimmer', 'Giellesse Sideboards', 'https://zb-interieur.netlify.app/images/imp/giellesse/giellesse-sideboards-2.webp', 'giellesse-sideboards-2.webp', 1800, 1172, 94524),
  (78, 'zb-upload:/images/imp/giellesse/giellesse-sideboards-3.webp', 'Giellesse', 'Sideboard', 'Wohnzimmer', 'Giellesse Sideboards', 'https://zb-interieur.netlify.app/images/imp/giellesse/giellesse-sideboards-3.webp', 'giellesse-sideboards-3.webp', 1800, 1172, 96224),
  (79, 'zb-upload:/images/imp/giellesse/giellesse-sideboards-4.webp', 'Giellesse', 'Sideboard', 'Wohnzimmer', 'Giellesse Sideboards', 'https://zb-interieur.netlify.app/images/imp/giellesse/giellesse-sideboards-4.webp', 'giellesse-sideboards-4.webp', 1800, 1172, 132144),
  (80, 'zb-upload:/images/imp/giellesse/giellesse-sideboards-5.webp', 'Giellesse', 'Sideboard', 'Wohnzimmer', 'Giellesse Sideboards', 'https://zb-interieur.netlify.app/images/imp/giellesse/giellesse-sideboards-5.webp', 'giellesse-sideboards-5.webp', 1800, 1172, 116254),
  (81, 'zb-upload:/images/imp/giellesse/giellesse-sideboards-6.webp', 'Giellesse', 'Regal', 'Wohnzimmer', 'Giellesse Sideboards', 'https://zb-interieur.netlify.app/images/imp/giellesse/giellesse-sideboards-6.webp', 'giellesse-sideboards-6.webp', 1800, 1172, 167804),
  (82, 'zb-upload:/images/imp/giellesse/giellesse-sideboards-7.webp', 'Giellesse', 'Sideboard', 'Wohnzimmer', 'Giellesse Sideboards', 'https://zb-interieur.netlify.app/images/imp/giellesse/giellesse-sideboards-7.webp', 'giellesse-sideboards-7.webp', 1800, 1172, 169132),
  (83, 'zb-upload:/images/imp/giellesse/giellesse-sideboards-8.webp', 'Giellesse', 'Regal', 'Wohnzimmer', 'Giellesse Sideboards', 'https://zb-interieur.netlify.app/images/imp/giellesse/giellesse-sideboards-8.webp', 'giellesse-sideboards-8.webp', 1800, 1200, 148090),
  (84, 'zb-upload:/images/imp/giellesse/night-collections.webp', 'Giellesse', 'Schrank', 'Schlafzimmer', 'Night Collections', 'https://zb-interieur.netlify.app/images/imp/giellesse/night-collections.webp', 'night-collections.webp', 1800, 1172, 148426),
  (85, 'zb-upload:/images/imp/giellesse/runder-tisch.webp', 'Giellesse', 'Tisch', 'Esszimmer', 'Runder Tisch', 'https://zb-interieur.netlify.app/images/imp/giellesse/runder-tisch.webp', 'runder-tisch.webp', 1382, 1800, 302294),
  (86, 'zb-upload:/images/imp/giellesse/schlafraum.webp', 'Giellesse', 'Bett', 'Schlafzimmer', 'Schlafraum', 'https://zb-interieur.netlify.app/images/imp/giellesse/schlafraum.webp', 'schlafraum.webp', 1800, 1200, 126450),
  (87, 'zb-upload:/images/imp/giellesse/sideboard.webp', 'Giellesse', 'Sideboard', 'Wohnzimmer', 'Sideboard', 'https://zb-interieur.netlify.app/images/imp/giellesse/sideboard.webp', 'sideboard.webp', 1639, 926, 73568),
  (88, 'zb-upload:/images/imp/giellesse/sideboard-2.webp', 'Giellesse', 'Sideboard', 'Schlafzimmer', 'Sideboard', 'https://zb-interieur.netlify.app/images/imp/giellesse/sideboard-2.webp', 'sideboard-2.webp', 1800, 1290, 163370),
  (89, 'zb-upload:/images/imp/giellesse/sideboard-3.webp', 'Giellesse', 'Schrank', 'Wohnzimmer', 'Sideboard', 'https://zb-interieur.netlify.app/images/imp/giellesse/sideboard-3.webp', 'sideboard-3.webp', 1260, 1800, 292858),
  (90, 'zb-upload:/images/imp/gyform/achille.webp', 'Gyform', 'Sofa', 'Wohnzimmer', 'Achille', 'https://zb-interieur.netlify.app/images/imp/gyform/achille.webp', 'achille.webp', 1800, 1227, 229432),
  (91, 'zb-upload:/images/imp/gyform/achille-2.webp', 'Gyform', 'Sofa', 'Wohnzimmer', 'Achille', 'https://zb-interieur.netlify.app/images/imp/gyform/achille-2.webp', 'achille-2.webp', 1800, 940, 95364),
  (92, 'zb-upload:/images/imp/gyform/achille-3.webp', 'Gyform', 'Sofa', 'Wohnzimmer', 'Achille', 'https://zb-interieur.netlify.app/images/imp/gyform/achille-3.webp', 'achille-3.webp', 1800, 928, 136000),
  (93, 'zb-upload:/images/imp/gyform/camilla.webp', 'Gyform', 'Sessel', 'Wohnzimmer', 'Camilla', 'https://zb-interieur.netlify.app/images/imp/gyform/camilla.webp', 'camilla.webp', 1349, 1800, 371178),
  (94, 'zb-upload:/images/imp/gyform/chanel.webp', 'Gyform', 'Sessel', 'Outdoor', 'Chanel', 'https://zb-interieur.netlify.app/images/imp/gyform/chanel.webp', 'chanel.webp', 1800, 1568, 224084),
  (95, 'zb-upload:/images/imp/gyform/dea.webp', 'Gyform', 'Sessel', 'Wohnzimmer', 'Dea', 'https://zb-interieur.netlify.app/images/imp/gyform/dea.webp', 'dea.webp', 1800, 1425, 357290),
  (96, 'zb-upload:/images/imp/gyform/focus.webp', 'Gyform', 'Sofa', 'Wohnzimmer', 'Focus', 'https://zb-interieur.netlify.app/images/imp/gyform/focus.webp', 'focus.webp', 1800, 853, 101758),
  (97, 'zb-upload:/images/imp/gyform/letto.webp', 'Gyform', 'Bett', 'Schlafzimmer', 'Letto', 'https://zb-interieur.netlify.app/images/imp/gyform/letto.webp', 'letto.webp', 1800, 853, 41608),
  (98, 'zb-upload:/images/imp/gyform/letto-2.webp', 'Gyform', 'Bett', 'Schlafzimmer', 'Letto', 'https://zb-interieur.netlify.app/images/imp/gyform/letto-2.webp', 'letto-2.webp', 850, 638, 24790),
  (99, 'zb-upload:/images/imp/gyform/lio.webp', 'Gyform', 'Sofa', 'Wohnzimmer', 'Lio', 'https://zb-interieur.netlify.app/images/imp/gyform/lio.webp', 'lio.webp', 1800, 1350, 293910),
  (100, 'zb-upload:/images/imp/gyform/lio-2.webp', 'Gyform', 'Sofa', 'Wohnzimmer', 'Lio', 'https://zb-interieur.netlify.app/images/imp/gyform/lio-2.webp', 'lio-2.webp', 1800, 1096, 194778),
  (101, 'zb-upload:/images/imp/gyform/motiv.webp', 'Gyform', 'Sessel', 'Wohnzimmer', 'Motiv', 'https://zb-interieur.netlify.app/images/imp/gyform/motiv.webp', 'motiv.webp', 1800, 1298, 99276),
  (102, 'zb-upload:/images/imp/gyform/mia.webp', 'Gyform', 'Sofa', 'Wohnzimmer', 'Mia', 'https://zb-interieur.netlify.app/images/imp/gyform/mia.webp', 'mia.webp', 1736, 1012, 258536),
  (103, 'zb-upload:/images/imp/gyform/mix.webp', 'Gyform', 'Sessel', 'Wohnzimmer', 'Mix', 'https://zb-interieur.netlify.app/images/imp/gyform/mix.webp', 'mix.webp', 1800, 1363, 42780),
  (104, 'zb-upload:/images/imp/gyform/mojito.webp', 'Gyform', 'Sofa', 'Wohnzimmer', 'Mojito', 'https://zb-interieur.netlify.app/images/imp/gyform/mojito.webp', 'mojito.webp', 1800, 1308, 249194),
  (105, 'zb-upload:/images/imp/gyform/mojito-2.webp', 'Gyform', 'Sofa', 'Wohnzimmer', 'Mojito', 'https://zb-interieur.netlify.app/images/imp/gyform/mojito-2.webp', 'mojito-2.webp', 1800, 1094, 301338),
  (106, 'zb-upload:/images/imp/gyform/morfeo.webp', 'Gyform', 'Sofa', 'Wohnzimmer', 'Morfeo', 'https://zb-interieur.netlify.app/images/imp/gyform/morfeo.webp', 'morfeo.webp', 1800, 1174, 308618),
  (107, 'zb-upload:/images/imp/gyform/morfeo-2.webp', 'Gyform', 'Sofa', 'Wohnzimmer', 'Morfeo', 'https://zb-interieur.netlify.app/images/imp/gyform/morfeo-2.webp', 'morfeo-2.webp', 1800, 1208, 195754),
  (108, 'zb-upload:/images/imp/gyform/morfeo-3.webp', 'Gyform', 'Sofa', 'Wohnzimmer', 'Morfeo', 'https://zb-interieur.netlify.app/images/imp/gyform/morfeo-3.webp', 'morfeo-3.webp', 1800, 1197, 307638),
  (109, 'zb-upload:/images/imp/gyform/nina.webp', 'Gyform', 'Sofa', 'Wohnzimmer', 'Nina', 'https://zb-interieur.netlify.app/images/imp/gyform/nina.webp', 'nina.webp', 1800, 1220, 339528),
  (110, 'zb-upload:/images/imp/gyform/oliver.webp', 'Gyform', 'Bett', 'Schlafzimmer', 'Oliver', 'https://zb-interieur.netlify.app/images/imp/gyform/oliver.webp', 'oliver.webp', 1800, 765, 138186),
  (111, 'zb-upload:/images/imp/gyform/oliver-2.webp', 'Gyform', 'Bett', 'Schlafzimmer', 'Oliver', 'https://zb-interieur.netlify.app/images/imp/gyform/oliver-2.webp', 'oliver-2.webp', 1800, 1200, 193120),
  (112, 'zb-upload:/images/imp/gyform/poncho.webp', 'Gyform', 'Sofa', 'Wohnzimmer', 'Poncho', 'https://zb-interieur.netlify.app/images/imp/gyform/poncho.webp', 'poncho.webp', 1800, 1051, 190916),
  (113, 'zb-upload:/images/imp/gyform/sophie.webp', 'Gyform', 'Sessel', 'Wohnzimmer', 'Sophie', 'https://zb-interieur.netlify.app/images/imp/gyform/sophie.webp', 'sophie.webp', 846, 933, 106500),
  (114, 'zb-upload:/images/imp/gyform/sophie-2.webp', 'Gyform', 'Sessel', 'Wohnzimmer', 'Sophie', 'https://zb-interieur.netlify.app/images/imp/gyform/sophie-2.webp', 'sophie-2.webp', 1800, 1568, 185944),
  (115, 'zb-upload:/images/imp/gyform/vogue.webp', 'Gyform', 'Sofa', 'Wohnzimmer', 'Vogue', 'https://zb-interieur.netlify.app/images/imp/gyform/vogue.webp', 'vogue.webp', 1800, 1321, 247130),
  (116, 'zb-upload:/images/imp/gyform/zeus.webp', 'Gyform', 'Sofa', 'Wohnzimmer', 'Zeus', 'https://zb-interieur.netlify.app/images/imp/gyform/zeus.webp', 'zeus.webp', 1800, 1276, 241814),
  (117, 'zb-upload:/images/imp/gyform/zeus-2.webp', 'Gyform', 'Sofa', 'Wohnzimmer', 'Zeus', 'https://zb-interieur.netlify.app/images/imp/gyform/zeus-2.webp', 'zeus-2.webp', 1800, 1199, 191176),
  (118, 'zb-upload:/images/imp/marchetti/copertina-copia.webp', 'Marchetti', 'Leuchte', '', 'Copertina Copia', 'https://zb-interieur.netlify.app/images/imp/marchetti/copertina-copia.webp', 'copertina-copia.webp', 1760, 1582, 234196),
  (119, 'zb-upload:/images/imp/marchetti/ice-ambient.webp', 'Marchetti', 'Leuchte', '', 'Ice Ambient', 'https://zb-interieur.netlify.app/images/imp/marchetti/ice-ambient.webp', 'ice-ambient.webp', 1240, 680, 65146),
  (120, 'zb-upload:/images/imp/marchetti/millennium.webp', 'Marchetti', 'Leuchte', '', 'Millennium', 'https://zb-interieur.netlify.app/images/imp/marchetti/millennium.webp', 'millennium.webp', 1440, 1029, 168694),
  (121, 'zb-upload:/images/imp/marchetti/rain-compo.webp', 'Marchetti', 'Leuchte', '', 'Rain Compo', 'https://zb-interieur.netlify.app/images/imp/marchetti/rain-compo.webp', 'rain-compo.webp', 1800, 1004, 61236),
  (122, 'zb-upload:/images/imp/marchetti/reflexa-oval.webp', 'Marchetti', 'Leuchte', '', 'Reflexa Oval', 'https://zb-interieur.netlify.app/images/imp/marchetti/reflexa-oval.webp', 'reflexa-oval.webp', 1800, 1119, 88380),
  (123, 'zb-upload:/images/imp/marchetti/diamante-swarovski-green-background.webp', 'Marchetti', 'Leuchte', '', 'Diamante Swarovski Green Background', 'https://zb-interieur.netlify.app/images/imp/marchetti/diamante-swarovski-green-background.webp', 'diamante-swarovski-green-background.webp', 1240, 680, 143646),
  (124, 'zb-upload:/images/imp/marchetti/essentia-s-gold-leaf-cover.webp', 'Marchetti', 'Leuchte', '', 'Essentia S Gold Leaf Cover', 'https://zb-interieur.netlify.app/images/imp/marchetti/essentia-s-gold-leaf-cover.webp', 'essentia-s-gold-leaf-cover.webp', 1240, 680, 123262),
  (125, 'zb-upload:/images/imp/marchetti/exagon-compo.webp', 'Marchetti', 'Leuchte', '', 'Exagon Compo', 'https://zb-interieur.netlify.app/images/imp/marchetti/exagon-compo.webp', 'exagon-compo.webp', 1240, 680, 110670),
  (126, 'zb-upload:/images/imp/marchetti/fall-compo.webp', 'Marchetti', 'Leuchte', '', 'Fall Compo', 'https://zb-interieur.netlify.app/images/imp/marchetti/fall-compo.webp', 'fall-compo.webp', 1240, 680, 96834),
  (127, 'zb-upload:/images/imp/marchetti/incanto-botto-view-b-oro.webp', 'Marchetti', 'Leuchte', '', 'Incanto Botto View B Oro', 'https://zb-interieur.netlify.app/images/imp/marchetti/incanto-botto-view-b-oro.webp', 'incanto-botto-view-b-oro.webp', 1200, 800, 128300),
  (128, 'zb-upload:/images/imp/marchetti/product-olympia.webp', 'Marchetti', 'Leuchte', '', 'Product Olympia', 'https://zb-interieur.netlify.app/images/imp/marchetti/product-olympia.webp', 'product-olympia.webp', 1240, 680, 208308),
  (129, 'zb-upload:/images/imp/marchetti/product-anime.webp', 'Marchetti', 'Leuchte', '', 'Product Anime', 'https://zb-interieur.netlify.app/images/imp/marchetti/product-anime.webp', 'product-anime.webp', 1240, 680, 151122),
  (130, 'zb-upload:/images/imp/marchetti/product-moule-gold.webp', 'Marchetti', 'Leuchte', '', 'Product Moule Gold', 'https://zb-interieur.netlify.app/images/imp/marchetti/product-moule-gold.webp', 'product-moule-gold.webp', 1240, 680, 131986),
  (131, 'zb-upload:/images/imp/marchetti/product-moule-naked.webp', 'Marchetti', 'Leuchte', '', 'Product Moule Naked', 'https://zb-interieur.netlify.app/images/imp/marchetti/product-moule-naked.webp', 'product-moule-naked.webp', 1240, 680, 51776),
  (132, 'zb-upload:/images/imp/marchetti/product-nashira-lumetto.webp', 'Marchetti', 'Leuchte', '', 'Product Nashira Lumetto', 'https://zb-interieur.netlify.app/images/imp/marchetti/product-nashira-lumetto.webp', 'product-nashira-lumetto.webp', 1240, 680, 44712),
  (133, 'zb-upload:/images/imp/marchetti/reflexa-ap-main.webp', 'Marchetti', 'Leuchte', '', 'Reflexa Ap Main', 'https://zb-interieur.netlify.app/images/imp/marchetti/reflexa-ap-main.webp', 'reflexa-ap-main.webp', 1240, 680, 115800),
  (134, 'zb-upload:/images/imp/marchetti/reflexa-compo-main.webp', 'Marchetti', 'Leuchte', '', 'Reflexa Compo Main', 'https://zb-interieur.netlify.app/images/imp/marchetti/reflexa-compo-main.webp', 'reflexa-compo-main.webp', 1240, 680, 75456),
  (135, 'zb-upload:/images/imp/marchetti/rim-main.webp', 'Marchetti', 'Leuchte', '', 'Rim Main', 'https://zb-interieur.netlify.app/images/imp/marchetti/rim-main.webp', 'rim-main.webp', 1240, 680, 175538),
  (136, 'zb-upload:/images/imp/marchetti/suspension-lamp.webp', 'Marchetti', 'Leuchte', '', 'Suspension Lamp', 'https://zb-interieur.netlify.app/images/imp/marchetti/suspension-lamp.webp', 'suspension-lamp.webp', 1240, 680, 127196),
  (137, 'zb-upload:/images/imp/marchetti/track-compo.webp', 'Marchetti', 'Leuchte', '', 'Track Compo', 'https://zb-interieur.netlify.app/images/imp/marchetti/track-compo.webp', 'track-compo.webp', 1240, 680, 38424),
  (138, 'zb-upload:/images/imp/rohleder/cloud.webp', 'Rohleder', 'Accessoire', '', 'Cloud', 'https://zb-interieur.netlify.app/images/imp/rohleder/cloud.webp', 'cloud.webp', 800, 800, 91658),
  (139, 'zb-upload:/images/imp/rohleder/kollektion-heimatliebe.webp', 'Rohleder', 'Accessoire', '', 'Kollektion Heimatliebe', 'https://zb-interieur.netlify.app/images/imp/rohleder/kollektion-heimatliebe.webp', 'kollektion-heimatliebe.webp', 800, 800, 90186),
  (140, 'zb-upload:/images/imp/rohleder/kollektion-patch.webp', 'Rohleder', 'Accessoire', '', 'Kollektion Patch', 'https://zb-interieur.netlify.app/images/imp/rohleder/kollektion-patch.webp', 'kollektion-patch.webp', 800, 800, 19858),
  (141, 'zb-upload:/images/imp/rohleder/kollektion-savannah.webp', 'Rohleder', 'Accessoire', '', 'Kollektion Savannah', 'https://zb-interieur.netlify.app/images/imp/rohleder/kollektion-savannah.webp', 'kollektion-savannah.webp', 630, 630, 82212),
  (142, 'zb-upload:/images/imp/rohleder/kollektion-tulum.webp', 'Rohleder', 'Accessoire', '', 'Kollektion Tulum', 'https://zb-interieur.netlify.app/images/imp/rohleder/kollektion-tulum.webp', 'kollektion-tulum.webp', 800, 800, 87796),
  (143, 'zb-upload:/images/imp/rohleder/kollektion-journey.webp', 'Rohleder', 'Accessoire', '', 'Kollektion Journey', 'https://zb-interieur.netlify.app/images/imp/rohleder/kollektion-journey.webp', 'kollektion-journey.webp', 800, 800, 158636),
  (144, 'zb-upload:/images/imp/rohleder/kollektion-studioline.webp', 'Rohleder', 'Accessoire', '', 'Kollektion Studioline', 'https://zb-interieur.netlify.app/images/imp/rohleder/kollektion-studioline.webp', 'kollektion-studioline.webp', 800, 800, 90990),
  (145, 'zb-upload:/images/imp/rohleder/lori-weitzner.webp', 'Rohleder', 'Accessoire', '', 'Lori Weitzner', 'https://zb-interieur.netlify.app/images/imp/rohleder/lori-weitzner.webp', 'lori-weitzner.webp', 1000, 1000, 65834),
  (146, 'zb-upload:/images/imp/rohleder/lounge.webp', 'Rohleder', 'Accessoire', '', 'Lounge', 'https://zb-interieur.netlify.app/images/imp/rohleder/lounge.webp', 'lounge.webp', 800, 800, 57946),
  (147, 'zb-upload:/images/imp/rohleder/lounge-pouf.webp', 'Rohleder', 'Accessoire', '', 'Lounge Pouf', 'https://zb-interieur.netlify.app/images/imp/rohleder/lounge-pouf.webp', 'lounge-pouf.webp', 600, 780, 43578),
  (148, 'zb-upload:/images/imp/rohleder/ocean.webp', 'Rohleder', 'Accessoire', '', 'Ocean', 'https://zb-interieur.netlify.app/images/imp/rohleder/ocean.webp', 'ocean.webp', 800, 800, 110150),
  (149, 'zb-upload:/images/imp/rohleder/plaids.webp', 'Rohleder', 'Accessoire', '', 'Plaids', 'https://zb-interieur.netlify.app/images/imp/rohleder/plaids.webp', 'plaids.webp', 600, 900, 49758),
  (150, 'zb-upload:/images/imp/rohleder/rewound.webp', 'Rohleder', 'Accessoire', '', 'Rewound', 'https://zb-interieur.netlify.app/images/imp/rohleder/rewound.webp', 'rewound.webp', 1600, 1600, 251650),
  (151, 'zb-upload:/images/imp/rohleder/soul.webp', 'Rohleder', 'Accessoire', '', 'Soul', 'https://zb-interieur.netlify.app/images/imp/rohleder/soul.webp', 'soul.webp', 660, 660, 66758),
  (152, 'zb-upload:/images/imp/rohleder/cloud-2.webp', 'Rohleder', 'Accessoire', '', 'Cloud', 'https://zb-interieur.netlify.app/images/imp/rohleder/cloud-2.webp', 'cloud-2.webp', 600, 750, 44874),
  (153, 'zb-upload:/images/imp/rohleder/cocoon-uni.webp', 'Rohleder', 'Accessoire', '', 'Cocoon Uni', 'https://zb-interieur.netlify.app/images/imp/rohleder/cocoon-uni.webp', 'cocoon-uni.webp', 800, 800, 73498),
  (154, 'zb-upload:/images/imp/rohleder/wabi-sabi.webp', 'Rohleder', 'Accessoire', '', 'Wabi Sabi', 'https://zb-interieur.netlify.app/images/imp/rohleder/wabi-sabi.webp', 'wabi-sabi.webp', 1200, 1800, 189844)
) as p(ord, key, brand, type, room, name, url, filename, width, height, size)
where not exists (
  select 1 from public.images i
  where i.tenant_id = (select id from public.tenants where slug = 'digitale-medien-319ef552') and i.external_id = p.key
);

-- Neue Auswahlwerte für Produktart und Bereich (nur falls noch nicht vorhanden)
insert into public.categories (tenant_id, slot, name, slug, sort_order)
select (select id from public.tenants where slug = 'digitale-medien-319ef552'), v.slot, v.name, trim(both '-' from regexp_replace(lower(v.name), '[^a-z0-9]+', '-', 'g')) || '-' || v.slot, 20
from (values (2, 'Tisch'), (2, 'Sideboard'), (2, 'Regal'), (2, 'Sofa'), (2, 'Stuhl'), (2, 'Bett'), (2, 'Sessel'), (2, 'Daybed'), (2, 'Schrank'), (2, 'Leuchte'), (2, 'Accessoire'), (3, 'Esszimmer'), (3, 'Wohnzimmer'), (3, 'Flur'), (3, 'Schlafzimmer'), (3, 'Outdoor')) as v(slot, name)
where not exists (
  select 1 from public.categories c
  where c.tenant_id = (select id from public.tenants where slug = 'digitale-medien-319ef552') and c.slot = v.slot and lower(trim(c.name)) = lower(v.name)
)
on conflict do nothing;

-- Kontrolle
select category1 as marke, count(*) as bilder from public.images
where tenant_id = (select id from public.tenants where slug = 'digitale-medien-319ef552') and external_id like 'zb-upload:%'
group by category1 order by category1;
