/** Default ZB Interieur media categories (extensible via API / categories.json). */

import type { MediaCategories } from './types.js'

export const DEFAULT_CATEGORIES: MediaCategories = {
  category1: [
    'FÍNE',
    'Fine',
    'AL2',
    'Gyform',
    'Giorgetti',
    'Gervasoni',
    'Kristalia',
    'Varaschin',
    'Möller Design',
    'Papadatos',
    'Bonaldo',
    'Marchetti',
    'Mogg',
    'Form exclusiv',
    'Piure',
    'Rohleder',
    'Nature Design',
    'Kolini',
    'Lema',
    'Limited Edition',
  ],
  category2: [
    'Sofa',
    'Sessel',
    'Stuhl',
    'Tisch',
    'Bett',
    'Schrank',
    'Leuchte',
    'Accessoire',
    'Outdoor',
    'Daybed',
    'Sideboard',
    'Teppich',
    'Sonstiges',
  ],
  category3: [
    'Wohnzimmer',
    'Esszimmer',
    'Schlafzimmer',
    'Büro',
    'Outdoor',
    'Objekte',
    'Bad',
    'Flur',
    'Showroom',
  ],
  category4: [
    'Designklassiker',
    'Modern',
    'Minimalistisch',
    'Luxus',
    'Outdoor',
    'Neuheiten',
    'Bestseller',
    'Zeitlos',
    'Skulptural',
  ],
}
