/** Default ZB Interieur media categories — category1 = real catalog brands only. */

import type { MediaCategories } from './types.js'

/** Hersteller / Marke — only brands that exist in marken-data. */
export const CATALOG_BRANDS = [
  'AL2',
  'ASA',
  'Biohort',
  'Bonaldo',
  'Brink & Campman',
  'Clarke & Clarke',
  'Fine',
  'fleuresse',
  'Form exclusiv',
  'Fürstenberg',
  'Giellesse',
  'Gyform',
  'Harlequin',
  'JAB Anstoetz',
  'Kolini',
  'La Vida',
  'Lema',
  'Limited Edition',
  'Lüönd',
  'Marchetti',
  'Mogg',
  'Möller Design',
  'naos',
  'Nature Design',
  'Papadatos',
  'Pozzebon',
  'Res Italia',
  'Rohleder',
  'Sitzwerk',
  'Unopiu',
  'Varaschin',
] as const

export const DEFAULT_CATEGORIES: MediaCategories = {
  category1: [...CATALOG_BRANDS],
  category2: [
    'Sofa',
    'Sessel',
    'Stuhl',
    'Tisch',
    'Bett',
    'Schrank',
    'Leuchte',
    'Accessoire',
    'Outdoor',
  ],
  category3: [
    'Wohnzimmer',
    'Esszimmer',
    'Schlafzimmer',
    'Büro',
    'Outdoor',
    'Objekte',
  ],
  category4: [
    'Designklassiker',
    'Modern',
    'Minimalistisch',
    'Luxus',
    'Outdoor',
    'Neuheiten',
    'Bestseller',
  ],
}
